# -*- coding: utf-8 -*-
"""1_trustedZone_Control.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TlA9aUcz153VzC48-d7NvdG91UtxzYHs

"""### Library Importation"""

import duckdb
import Zones.config as conf

def trustedZone_control():

    """### DB Mounting"""

    dbFile_trusted = conf.DBFILE_TRUSTED_ZONE_PATH

    con_trusted = duckdb.connect(dbFile_trusted)

    """## Creation of Control Tables

    ### Creation of the TABLES_LOADED table
    """
    cursor = con_trusted.cursor()

    cursor.execute('CREATE TABLE IF NOT EXISTS tables_loaded (id UBIGINT PRIMARY KEY ,  tablename VARCHAR, load_date DATETIME ) ')
    cursor.execute('CREATE SEQUENCE IF NOT EXISTS tables_loaded_id START 1')

    con_trusted.close()