# -*- coding: utf-8 -*-
"""4_trustedZone_SetCorrectFormats.ipynb

Automatically generated by Colaboratory

Original file is located at
    https://colab.research.google.com/drive/1LXxBnZ6jnQluUI9Gxef6IGjzCovpsXAo

"""

import duckdb
import pandas as pd
import Zones.config as conf


def trustedZone_setcorrectformats():

  dbFile_trusted = conf.DBFILE_TRUSTED_ZONE_PATH

  con_trusted = duckdb.connect(dbFile_trusted)
  cursor_trusted = con_trusted.cursor()

  """### Set correct formats"""

  #Get all tablenames
  tablenames=cursor_trusted.execute('select tablename from pg_tables').fetchdf()

  print('---------------------------')
  print('Set Correct Formats Report')
  print('---------------------------')

  #Show all tables
  for table in tablenames['tablename']:
    aux = cursor_trusted.execute('select * from '+table).fetchdf()
    print(f"Table {table}")
    flagChanged=False
    for column_name in aux:
      try:
        aux[column_name] = aux[column_name].apply(lambda x: x.replace(",","."))
        aux[column_name] = pd.to_numeric(aux[column_name])
        print(f"\tColumn {column_name} converted to numeric")
        flagChanged=True
      except:
        continue
    if flagChanged:
      cursor_trusted.execute('drop table '+table)
      cursor_trusted.execute('create table  '+table+ ' as select * from aux')

  """### Closing DB Connection"""

  con_trusted.close()